### PR TITLE
Fix tabs re-order

### LINKED ISSUE #415: Order of Training tabs cannot be rearranged
image

When entries on the "Manage Tabs" modal are rearranged, the changes are not saved and the tabs are still in the original order.

### PR DESCRIPTION
**Pull request by allenwq**
Fix #415

### CODE REVIEW

File: app/controllers/tabs/tabs_controller.rb [hunk 1]
```diff
@@ -78,6 +78,13 @@ def update
     end
   end
 
+  def sort
+    params[:order].each do |_key, value|
+      Tab.find(value[:id]).update_column(:pos, value[:position])
```
Comment (jsyeo) [inline app/controllers/tabs/tabs_controller.rb]: Probably gonna need a better name than `value`. I am not sure what is it until I read the javascript code.

Comment (jsyeo) [inline app/controllers/tabs/tabs_controller.rb]: How about `tab`? While you're at it, rename `_key` to  `_`.
